language: node_js
node_js:
  - "8.9.4"

postgres:
  adapter: postgresql
  database: fast-food-fast
  username: postgres
services:
  - postgresql
global:
 - export SET NODE_ENV=test
before_script:
  - npm install
  - "psql -c 'create database fast-food-fast;' -U postgres"
  - "rake db:migrate"
script:
  - npm test
after_script:
  - npm run coverage
cache:
  directories:
    - "node_modules"
  yarn: true

