language: node_js
node_js:
  - "8.9.4"
services:
  - postgresql
global:
 - export SET NODE_ENV=test
before_script:
  - npm install
  - npm run drop
  - npm run migration
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
script:
  -npm run migration
  - npm test
after_script:
  - npm run coverage
cache:
  directories:
    - "node_modules"
  yarn: true


